FROM apache/airflow:3.1.3

# Switch to airflow user (REQUIRED)
USER airflow

# Install Python dependencies as airflow user
RUN pip install --no-cache-dir \
    mlflow==3.7.0 \
    psycopg2-binary \
    boto3
